const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  // USER
  GET_CURRENT: "GET_CURRENT",
  // GET POST REALESTATE
  GET_POST_REALESTATE: "GET_POST_REALESTATE",
  SET_LOADING: "SET_LOADING",
  GET_POST_REALESTATE_BY_ID: "GET_POST_REALESTATE_BY_ID",
  GET_REAL_ESTATE_BY_BUSSINESS_TYPE_ID: "GET_REAL_ESTATE_BY_BUSSINESS_TYPE_ID",
};

export default actionTypes;
