const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  // USER
  GET_CURRENT: "GET_CURRENT",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
  GET_ALL_USER: "GET_ALL_USER",
  // GET POST REALESTATE
  GET_POST_REALESTATE: "GET_POST_REALESTATE",
  SET_LOADING: "SET_LOADING",
  GET_POST_REALESTATE_BY_ID: "GET_POST_REALESTATE_BY_ID",
  GET_REAL_ESTATE_BY_BUSSINESS_TYPE_ID: "GET_REAL_ESTATE_BY_BUSSINESS_TYPE_ID",
  GET_REAL_ESTATE_BY_TYPE_DETAILID: "GET_REAL_ESTATE_BY_TYPE_DETAILID",

  DELETE_REALESTATE_TYPE_SUCCESS: "DELETE_REALESTATE_TYPE_SUCCESS",
  DELETE_REALESTATE_TYPE_FAILER: "DELETE_REALESTATE_TYPE_FAILER",

  // FAVORITE
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  REMOVE_ALL_FAVORITES: "REMOVE_ALL_FAVORITES",

  //
  GET_FILTER_REAL_ESTATE_SUCCESS: "GET_FILTER_REAL_ESTATE_SUCCESS",
  GET_FILTER_REAL_ESTATE_FAILURE: "GET_FILTER_REAL_ESTATE_FAILURE",
  //
  GET_REAL_ESTATE_BY_USERID: "GET_REAL_ESTATE_BY_USERID",
  //
  DELETE_REAL_ESTATE_BY_USERID_SUCCESS: "DELETE_REAL_ESTATE_BY_USERID_SUCCESS",
  DELETE_REAL_ESTATE_BY_USERID_FAILURE: "DELETE_REAL_ESTATE_BY_USERID_FAILURE",

  // AUCTION
  GET_ALL_AUCTION: "GET_ALL_AUCTION",
  GET_AUCTION_BY_ID: "GET_AUCTION_BY_ID",
  REGISTER_AUCTION_SUCCESS: "REGISTER_AUCTION_SUCCESS",
  REGISTER_AUCTION_FAILURE: "REGISTER_AUCTION_FAILURE",
  GET_AUCTION_BY_USERID: "GET_AUCTION_BY_USERID",
  GET_AUCTION_REGISTER_OF_USER: "GET_AUCTION_REGISTER_OF_USER",

  POST_BARGAIN_AUCTION_SUCCESS: "POST_BARGAIN_AUCTION_SUCCESS",
  POST_BARGAIN_AUCTION_FAILER: "POST_BARGAIN_AUCTION_FAILER",
  GET_BARGAINAUCTION_BY_ID: "GET_BARGAINAUCTION_BY_ID",
  GET_ALL_REGISTER_AUCTION: "GET_ALL_REGISTER_AUCTION",

  // APPROVAL AUCTION
  APPROVAL_AUCTION_SUCCESS: "APPROVAL_AUCTION_SUCCESS",
  APPROVAL_AUCTION_FAILER: "APPROVAL_AUCTION_FAILER",
  // PHÊ DUYỆT NGƯỜI DÙNG ĐĂNG KÍ THAM GIA ĐẤU GIÁ
  APPROVAL_AUCTION_REGISTER_SUCCESS: "APPROVAL_AUCTION_REGISTER_SUCCESS",
  APPROVAL_AUCTION_REGISTER_FAILER: "APPROVAL_AUCTION_REGISTER_FAILER",
  //Xoá phê duyệt đăng kí
  DELETE_APPROVAL_AUCTION_REGISTER_SUCCESS:
    "DELETE_APPROVAL_AUCTION_REGISTER_SUCCESS",
  DELETE_APPROVAL_AUCTION_REGISTER_FAILER:
    "DELETE_APPROVAL_AUCTION_REGISTER_FAILER",
  //Xoá phê duyệt tin đănng
  DELETE_APPROVAL_AUCTION_SUCCESS: "DELETE_APPROVAL_AUCTION_SUCCESS",
  DELETE_APPROVAL_AUCTION_FAILER: "DELETE_APPROVAL_AUCTION_FAILER",
  // Xoá user by id
  DELETE_USER_BY_ADMIN_SUCCESS: "DELETE_USER_BY_ADMIN_SUCCESS",
  DELETE_USER_BY_ADMIN_FAILER: "DELETE_USER_BY_ADMIN_FAILER",
  //KẾT QUẢ NGƯỜI CHIẾN THẮNG
  AUCTION_RESULT_SUCCESS: "ACTION_RESULT_SUCCESS",
  AUCTION_RESULT_FAILER: "ACTION_RESULT_FAILER",

  GET_ALL_AUCTION_RESULT: "GET_ALL_AUCTION_RESULT",
};

export default actionTypes;
